# Generated by Django 2.1.7 on 2019-03-07 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=50)),
                ('competition_rank', models.CharField(choices=[('WChamp', 'World Championship'), ('WCup', 'World Cup'), ('NChamp', 'National Championship'), ('NCup', 'National Cup'), ('OT', 'Other')], max_length=20)),
                ('discipline', models.CharField(choices=[('PP', 'Ping Pong'), ('T', 'Tennis'), ('BILL', 'Billiards'), ('B', 'Badminton'), ('S', 'Squash'), ('D', 'Darts'), ('O', 'Other')], default='PP', max_length=20)),
                ('competition_date', models.DateField(help_text='Please use the following format: YYYY-MM-DD.')),
                ('description', models.TextField(blank=True)),
                ('applications_deadline', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/%Y/%m/%d')),
                ('competitors', models.ManyToManyField(blank=True, related_name='event_competitors', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
