# Generated by Django 2.1.7 on 2019-03-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-competition_date',)},
        ),
        migrations.AddField(
            model_name='event',
            name='max_number_competitors',
            field=models.PositiveIntegerField(choices=[(4, '4'), (8, '8'), (16, '16'), (32, '32'), (64, '64'), (128, '128')], default=16),
        ),
    ]
