# Generated by Django 2.1.7 on 2019-04-07 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20190309_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_rank', models.CharField(max_length=30)),
                ('cup', models.ImageField(blank=True, upload_to='cups/')),
            ],
        ),
        migrations.CreateModel(
            name='MaxEventCompetitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_competitors', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_number_competitors',
        ),
        migrations.AlterField(
            model_name='event',
            name='competition_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='competition_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.EventRank'),
        ),
        migrations.AlterField(
            model_name='event',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.EventDiscipline'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_competitors',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='competition.MaxEventCompetitors'),
            preserve_default=False,
        ),
    ]
