# Generated by Django 2.1.7 on 2019-04-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20190407_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_competitors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MaxEventCompetitors',
        ),
    ]
