# Generated by Django 2.1.7 on 2019-03-09 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0002_auto_20190309_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_1_won_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('round_2_won_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('round_3_won_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('round_4_won_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('round_5_won_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('round_6_won_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('round_7_won_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('round_8_won_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Event')),
                ('round_1_competitors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_1_competitors', to=settings.AUTH_USER_MODEL)),
                ('round_2_competitors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_2_competitors', to=settings.AUTH_USER_MODEL)),
                ('round_3_competitors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_3_competitors', to=settings.AUTH_USER_MODEL)),
                ('round_4_competitors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_4_competitors', to=settings.AUTH_USER_MODEL)),
                ('round_5_competitors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_5_competitors', to=settings.AUTH_USER_MODEL)),
                ('round_6_competitors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_6_competitors', to=settings.AUTH_USER_MODEL)),
                ('round_7_competitors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_7_competitors', to=settings.AUTH_USER_MODEL)),
                ('round_8_competitors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_8_competitors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
