# Generated by Django 2.1.7 on 2019-03-09 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0002_auto_20190309_0720'),
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_won_sets', models.PositiveIntegerField(default=0)),
                ('player2_won_sets', models.PositiveIntegerField(default=0)),
                ('points_player1_set1', models.PositiveIntegerField(blank=True, null=True)),
                ('points_player1_set2', models.PositiveIntegerField(blank=True, null=True)),
                ('points_player1_set3', models.PositiveIntegerField(blank=True, null=True)),
                ('points_player1_set4', models.PositiveIntegerField(blank=True, null=True)),
                ('points_player1_set5', models.PositiveIntegerField(blank=True, null=True)),
                ('points_player2_set1', models.PositiveIntegerField(blank=True, null=True)),
                ('points_player2_set2', models.PositiveIntegerField(blank=True, null=True)),
                ('points_player2_set3', models.PositiveIntegerField(blank=True, null=True)),
                ('points_player2_set4', models.PositiveIntegerField(blank=True, null=True)),
                ('points_player2_set5', models.PositiveIntegerField(blank=True, null=True)),
                ('played', models.DateField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Event')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-played',),
            },
        ),
    ]
