# Generated by Django 2.1.7 on 2019-03-11 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1_score', models.PositiveIntegerField(blank=True, null=True)),
                ('player_2_score', models.PositiveIntegerField(blank=True, null=True)),
                ('number_set', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='points_player1_set1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='points_player1_set2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='points_player1_set3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='points_player1_set4',
        ),
        migrations.RemoveField(
            model_name='match',
            name='points_player1_set5',
        ),
        migrations.RemoveField(
            model_name='match',
            name='points_player2_set1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='points_player2_set2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='points_player2_set3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='points_player2_set4',
        ),
        migrations.RemoveField(
            model_name='match',
            name='points_player2_set5',
        ),
        migrations.AddField(
            model_name='set',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Match'),
        ),
    ]
